name: dars_workspace
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/dars
  - packages/dars_test

dev_dependencies:
  args: ^2.7.0
  coverage: ^1.15.0
  test: ^1.25.6
  yaml: ^3.1.3
